insert into product 
(id,name,description,price)
values
(gen_random_uuid(),'ALGODÃO APOLO','ALGODÃO APOLO - CAIXA 25 GR', 12.90),
(gen_random_uuid(),'ALGODÃO APOLO','ALGODÃO APOLO MULTIUSO - CAIXA 50 GR', 23.00),
(gen_random_uuid(),'ALGODÃO APOLO','ALGODÃO APOLO MULTIUSO - CAIXA 50 GR', 20.00),
(gen_random_uuid(),'ESCOVA DENTAL','ESCOVA DENTAL COLGATE SENSITIVE - PCT 1', 7.50),
(gen_random_uuid(),'CREME DENTAL','CREME DENTAL COLGATE LUMINOUS WHITE', 11.35),
(gen_random_uuid(),'CREME DENTAL','CREME DENTAL ELMEX SENSITIVE', 7.50),
(gen_random_uuid(),'SABONETE LÍQUIDO','SABONETE LÍQUIDO PROTEX BABY', 8.72),
(gen_random_uuid(),'SABONETE LÍQUIDO','SABONETE LÍQUIDO GRANADO GLICERINA', 11.72),
(gen_random_uuid(),'SABONETE','SABONETE GRANADO COCO 100G', 5.50),
(gen_random_uuid(),'CREME DENTAL','CREME DENTAL ELMEX SENSITIVE', 7.50),
(gen_random_uuid(),'TALCO','TALCO GRANADO BEBÊ', 15.35),
(gen_random_uuid(),'CONDICIONADOR','CONDICIONADOR TRESEMME BAIXO POO 400ML', 12.72),
(gen_random_uuid(),'SHAMPOO','SHAMPOO CLEAR HIDRATAÇÃO 400ML', 8.55),
(gen_random_uuid(),'SHAMPOO','SHAMPOO CLEAR CONTROLE QUEDA', 8.55),
(gen_random_uuid(),'SHAMPOO','SHAMPOO LIMPEZA DIÁRIA', 7.30),
(gen_random_uuid(),'DESODORANTE','DESODORANTE AXE AERO URBAN MAN 152ML', 7.20),
(gen_random_uuid(),'DESODORANTE','DESODORANTE SUAVE AERO INVIS 200ML', 7.20),
(gen_random_uuid(),'DESODORANTE','DESODORANTE REXONA ROLLON ACT', 11.20),
(gen_random_uuid(),'DESODORANTE','DESODORANTE AXE AERO URBAN MAN 152ML', 7.20),
(gen_random_uuid(),'DESODORANTE','DESODORANTE AXE AERO ANTIBAC 150ML', 5.20),
(gen_random_uuid(),'METFORMINA','METFORMINA (CLORIDRATO) COMPRIMIDO 850 MG', 25.20),
(gen_random_uuid(),'METARAMINOL','METARAMINOL (HEMITARTARATO) SOLUCAO INJETAVEL 10 MG/ML', 38.20),
(gen_random_uuid(),'METADONA','METADONA (CLORIDRATO) COMPRIMIDO 10 MG',22.00),
(gen_random_uuid(),'MEBENDAZOL','MEBENDAZOL SUSPENSAO ORAL 100 MG/5ML FRASCO 30 ML COM DOSEADOR',35.00),
(gen_random_uuid(),'MANITOL','MANITOL SOLUCAO INJETAVEL 200 MG/ML BOLSA OU FRASCO 250 ML SISTEMA
FECHADO DE INFUSAO',55.72);