create table product (
    id uuid PRIMARY key,
    name varchar(50) NOT null DEFAULT '',
    description varchar(255) NOT null DEFAULT '',
    "price" numeric(9,2) NOT null DEFAULT 0
);
create table "order" (
	id uuid primary key,
	createdAt timestamp not null default CURRENT_TIMESTAMP,
	updatedAt timestamp null, 
	status smallint not null default 1	
);
create table orderitem (
	idOrder uuid not null,
	idProduct uuid not null,
	quantity decimal(9,2) not null default 1,
	constraint pk_orderitem primary key(idOrder,idProduct),
	constraint fk_order foreign key (idOrder) references "order"(id),
	constraint fk_product foreign key (idProduct) references "product"(id)
);
create table orderProcessingAttempt(
	id bigint generated by default as identity primary key not null,
	idOrder uuid not null,
	attemptNumber int not null default 1,
	startedAt timestamp not null default CURRENT_TIMESTAMP,
	finishedAt timestamp null,
	success boolean not null default true,
	errorMessage varchar(75) null,
	constraint fk_order foreign key (idOrder) references "order"(id)
);

